// reportBuilder.ts — HTML Report Generator
// Takes the AI analysis output + crawl data and renders a polished,
// self-contained HTML report. This is the product — the report must
// stand on its own without explanation.

import { AuditRow, getCrawlPages } from './database';
import { AnalysisResult, Scorecard, AnalysisIssue } from './analyser';
import { ConsentResult } from './crawler';
import { ScorecardResult, CheckResult, CheckCategory } from './checks';
import path from 'path';
import fs from 'fs';

// ─── Main export ────────────────────────────────────────────────────────────

/**
 * Generate a complete HTML report from the AI analysis and crawl data.
 * Returns a self-contained HTML string ready to serve.
 */
export function buildReport(
  audit: AuditRow,
  analysis: AnalysisResult,
  scorecard: Scorecard,
  consentData: ConsentResult | null
): string {
  const crawlPages = getCrawlPages(audit.id).filter(p => p.page_type !== 'consent_check');
  const auditDate = new Date(audit.created_at).toLocaleDateString('en-IE', {
    day: 'numeric', month: 'long', year: 'numeric',
  });

  // Group issues by category
  const issuesByCategory: Record<string, AnalysisIssue[]> = {};
  for (const issue of analysis.issues) {
    const cat = issue.category || 'Other';
    if (!issuesByCategory[cat]) issuesByCategory[cat] = [];
    issuesByCategory[cat].push(issue);
  }

  // Sort categories: put categories with critical issues first
  const severityRank: Record<string, number> = { critical: 4, high: 3, medium: 2, low: 1 };
  const sortedCategories = Object.entries(issuesByCategory).sort((a, b) => {
    const aMax = Math.max(...a[1].map(i => severityRank[i.severity] || 0));
    const bMax = Math.max(...b[1].map(i => severityRank[i.severity] || 0));
    return bMax - aMax;
  });

  // Get homepage screenshot
  const homepageCrawl = crawlPages.find(p => p.page_type === 'homepage');
  const homepageScreenshot = homepageCrawl?.screenshot_path || null;

  // Count issues for dynamic CTA
  const totalIssues = analysis.issues.length;
  const criticalOrHigh = analysis.issues.filter(i => i.severity === 'critical' || i.severity === 'high').length;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tracking Health Audit — ${escHtml(audit.website_url)} | TrackGuard</title>
  <style>${reportCSS()}</style>
</head>
<body>
  <div class="report">
    <!-- Header -->
    ${renderHeader(audit, auditDate)}

    <!-- How to read this report -->
    <div class="how-to-read">
      This report was generated by an automated crawl of your public website. No access to your GA4 property or tag manager was required. All findings are based on externally observable tracking behaviour.
    </div>

    <!-- Scorecard -->
    ${renderScorecard(scorecard, analysis)}

    <!-- Data Impact (promoted to top) -->
    ${analysis.data_impact_summary ? renderDataImpact(analysis.data_impact_summary) : ''}

    <!-- Table of Contents -->
    ${renderTableOfContents(consentData)}

    <!-- Executive Summary -->
    ${renderExecutiveSummary(analysis)}

    <!-- Consent Analysis -->
    ${consentData ? renderConsentSection(consentData) : ''}

    <!-- Homepage Screenshot -->
    ${homepageScreenshot ? renderScreenshot(homepageScreenshot, 'Homepage at time of audit') : ''}

    <!-- Findings -->
    ${renderFindings(sortedCategories, crawlPages)}

    <!-- Positive Findings -->
    ${renderPositiveFindings(analysis.positive_findings)}

    <!-- Pages Crawled -->
    ${renderPagesSummary(crawlPages)}

    <!-- Limitations -->
    ${renderLimitations(analysis.limitations)}

    <!-- Footer -->
    ${renderFooter(audit, totalIssues, criticalOrHigh)}
  </div>
</body>
</html>`;
}

// ─── Section renderers ──────────────────────────────────────────────────────

function renderHeader(audit: AuditRow, auditDate: string): string {
  return `
    <header class="report-header">
      <div class="brand">Track<span class="brand-accent">Guard</span></div>
      <h1>Tracking Health Audit</h1>
      <div class="header-meta">
        <div class="meta-item"><span class="meta-label">Website</span><span class="meta-value">${escHtml(audit.website_url)}</span></div>
        <div class="meta-item"><span class="meta-label">Company</span><span class="meta-value">${escHtml(audit.company_name)}</span></div>
        <div class="meta-item"><span class="meta-label">Audit Date</span><span class="meta-value">${auditDate}</span></div>
        <div class="meta-item"><span class="meta-label">Reference</span><span class="meta-value">${escHtml(audit.reference_id)}</span></div>
      </div>
    </header>`;
}

function renderScorecard(scorecard: Scorecard, analysis: AnalysisResult): string {
  const scoreColor = scorecard.health_score >= 80 ? 'score-green'
    : scorecard.health_score >= 50 ? 'score-amber'
    : 'score-red';

  const totalIssues = scorecard.critical_count + scorecard.high_count + scorecard.medium_count + scorecard.low_count;

  return `
    <section class="scorecard">
      <div class="score-circle ${scoreColor}">
        <div class="score-number">${scorecard.health_score}</div>
        <div class="score-label">Health Score</div>
      </div>
      <div class="score-breakdown">
        <h2>Issue Summary</h2>
        <div class="severity-counts">
          ${scorecard.critical_count > 0 ? `<div class="sev-count sev-critical"><span class="sev-num">${scorecard.critical_count}</span><span class="sev-label">Critical</span></div>` : ''}
          ${scorecard.high_count > 0 ? `<div class="sev-count sev-high"><span class="sev-num">${scorecard.high_count}</span><span class="sev-label">High</span></div>` : ''}
          ${scorecard.medium_count > 0 ? `<div class="sev-count sev-medium"><span class="sev-num">${scorecard.medium_count}</span><span class="sev-label">Medium</span></div>` : ''}
          ${scorecard.low_count > 0 ? `<div class="sev-count sev-low"><span class="sev-num">${scorecard.low_count}</span><span class="sev-label">Low</span></div>` : ''}
          ${totalIssues === 0 ? `<div class="sev-count sev-none"><span class="sev-num">0</span><span class="sev-label">Issues</span></div>` : ''}
        </div>
        <div class="category-pills">
          ${Object.entries(scorecard.categories).map(([cat, data]) =>
            `<span class="cat-pill cat-${data.worst_severity}">${escHtml(cat)} (${data.issues})</span>`
          ).join('')}
        </div>
      </div>
    </section>`;
}

function renderDataImpact(summary: string): string {
  return `
    <section class="section data-impact-section" id="data-impact">
      <div class="data-impact-box">
        <div class="data-impact-icon">⚡</div>
        <div class="data-impact-content">
          <h2>What This Means for Your Data</h2>
          <p>${escHtml(summary)}</p>
        </div>
      </div>
    </section>`;
}

function renderTableOfContents(consentData: ConsentResult | null): string {
  return `
    <nav class="toc">
      <span class="toc-label">Jump to:</span>
      <a href="#executive-summary">Executive Summary</a>
      ${consentData ? '<a href="#consent-analysis">Consent Analysis</a>' : ''}
      <a href="#detailed-findings">Detailed Findings</a>
      <a href="#whats-working">What's Working</a>
      <a href="#pages-audited">Pages Audited</a>
      <a href="#limitations">Limitations</a>
    </nav>`;
}

function renderExecutiveSummary(analysis: AnalysisResult): string {
  return `
    <section class="section" id="executive-summary">
      <h2>Executive Summary</h2>
      <div class="summary-box">
        <p>${escHtml(analysis.executive_summary)}</p>
      </div>
    </section>`;
}

function renderConsentSection(consent: ConsentResult): string {
  if (!consent.bannerFound && !consent.defaultConsentState) {
    return `
    <section class="section" id="consent-analysis">
      <h2>Consent & Privacy</h2>
      <div class="alert alert-warning">
        <strong>No consent banner detected.</strong> The crawler did not find a recognisable consent management banner on the homepage. If this site serves EU visitors, this may be a GDPR compliance gap.
      </div>
    </section>`;
  }

  const consentKeys = ['ad_storage', 'analytics_storage', 'ad_user_data', 'ad_personalization',
    'functionality_storage', 'personalization_storage', 'security_storage'];

  const defaultState = consent.defaultConsentState || {};
  const postState = consent.postConsentState || {};

  // Filter to only consent-relevant keys
  const relevantDefault = Object.fromEntries(
    Object.entries(defaultState).filter(([k]) => consentKeys.includes(k))
  );
  const relevantPost = Object.fromEntries(
    Object.entries(postState).filter(([k]) => consentKeys.includes(k))
  );

  // Group post-consent GA4 requests: group unresolved events together
  const resolvedRequests: { label: string; measId: string }[] = [];
  const unresolvedByMeasId: Record<string, number> = {};
  for (const r of consent.postConsentGA4Requests) {
    const eventLabel = (r.event_names || []).join(', ');
    const measId = r.measurement_id || 'unknown ID';
    if (eventLabel && eventLabel !== '') {
      resolvedRequests.push({ label: eventLabel, measId });
    } else {
      unresolvedByMeasId[measId] = (unresolvedByMeasId[measId] || 0) + 1;
    }
  }

  return `
    <section class="section" id="consent-analysis">
      <h2>Consent & Privacy Analysis</h2>

      <div class="consent-meta">
        <span class="consent-badge">${escHtml(consent.cmpDetected || 'Unknown')} CMP</span>
        ${consent.acceptButtonClicked
          ? '<span class="consent-badge consent-ok">Accept All — Clicked ✓</span>'
          : '<span class="consent-badge consent-warn">Accept button not found</span>'}
      </div>

      ${consent.bannerScreenshot ? renderScreenshot(consent.bannerScreenshot, 'Consent banner as displayed to visitors') : ''}

      <h3>Before vs After Consent</h3>
      <div class="consent-table-wrap">
        <table class="consent-table">
          <thead>
            <tr>
              <th>Consent Parameter</th>
              <th>Default (Before)</th>
              <th>After Accept All</th>
              <th>Assessment</th>
            </tr>
          </thead>
          <tbody>
            ${consentKeys.map(key => {
              const before = relevantDefault[key] || '—';
              const after = relevantPost[key] || '—';
              let status = '';
              let statusClass = '';
              if (before === 'denied' && after === 'granted') {
                status = '✓ Correct';
                statusClass = 'consent-cell-ok';
              } else if (before === 'denied' && after === 'denied') {
                status = '⚠ Still denied';
                statusClass = 'consent-cell-warn';
              } else if (before === 'granted' && after === 'granted') {
                status = '⚠ No default deny';
                statusClass = 'consent-cell-warn';
              } else if ((before === '—' || before === 'undefined' || !before) && (after === '—' || after === 'undefined' || !after)) {
                status = 'Not configured';
                statusClass = 'consent-cell-missing';
              } else if ((before === '—' || before === 'undefined' || !before) && after === 'granted') {
                status = '⚠ No default denied state';
                statusClass = 'consent-cell-warn';
              } else if ((before === '—' || before === 'undefined' || !before) && after === 'denied') {
                status = '⚠ Not configured';
                statusClass = 'consent-cell-warn';
              } else {
                status = 'Inconclusive';
                statusClass = 'consent-cell-missing';
              }
              return `<tr>
                <td><code>${escHtml(key)}</code></td>
                <td class="${before === 'denied' ? 'consent-cell-denied' : before === 'granted' ? 'consent-cell-granted' : 'consent-cell-missing'}">${(!before || before === '—' || before === 'undefined') ? 'Not set' : escHtml(before)}</td>
                <td class="${after === 'denied' ? 'consent-cell-denied' : after === 'granted' ? 'consent-cell-granted' : 'consent-cell-missing'}">${(!after || after === '—' || after === 'undefined') ? 'Not set' : escHtml(after)}</td>
                <td class="${statusClass}">${status}</td>
              </tr>`;
            }).join('')}
          </tbody>
        </table>
      </div>

      ${consent.postConsentGA4Requests.length > 0 ? `
      <h3>Tags That Fired After Consent</h3>
      <p class="muted">These ${consent.postConsentGA4Requests.length} GA4/Google requests fired after the user clicked "Accept All" — confirming they are correctly gated behind consent.</p>
      <ul class="tag-list">
        ${resolvedRequests.slice(0, 10).map(r =>
          `<li><code>${escHtml(r.label)}</code> → ${escHtml(r.measId)}</li>`
        ).join('')}
        ${Object.entries(unresolvedByMeasId).map(([measId, count]) =>
          `<li><code>${count} unresolved event${count > 1 ? 's' : ''}</code> → ${escHtml(measId)}</li>`
        ).join('')}
        ${resolvedRequests.length > 10 ? `<li class="muted">…and ${resolvedRequests.length - 10} more named events</li>` : ''}
      </ul>` : ''}
    </section>`;
}

function renderFindings(
  sortedCategories: [string, AnalysisIssue[]][],
  crawlPages: any[]
): string {
  if (sortedCategories.length === 0) {
    return `
    <section class="section" id="detailed-findings">
      <h2>Detailed Findings</h2>
      <p>No issues were identified during this audit.</p>
    </section>`;
  }

  // Build a global issue counter across all categories
  let issueNumber = 0;

  return `
    <section class="section" id="detailed-findings">
      <h2>Detailed Findings</h2>
      ${sortedCategories.map(([category, issues]) => `
        <div class="category-group">
          <h3 class="category-title">${escHtml(category)}</h3>
          ${issues.map(issue => {
            issueNumber++;
            return renderIssueCard(issue, issueNumber);
          }).join('')}
        </div>
      `).join('')}
    </section>`;
}

function renderIssueCard(issue: AnalysisIssue, issueNumber: number): string {
  return `
    <div class="issue-card issue-${issue.severity}">
      <div class="issue-header">
        <span class="issue-number">Issue ${issueNumber}</span>
        <span class="severity-badge badge-${issue.severity}">${issue.severity.toUpperCase()}</span>
        <h4 class="issue-title">${escHtml(issue.title)}</h4>
      </div>
      <div class="issue-body">
        <div class="issue-section">
          <div class="issue-label">Evidence</div>
          <p>${escHtml(issue.evidence)}</p>
        </div>
        <div class="issue-section">
          <div class="issue-label">Business Impact</div>
          <p>${escHtml(issue.business_impact)}</p>
        </div>
        <div class="issue-section">
          <div class="issue-label">Recommendation</div>
          <p>${escHtml(issue.recommendation)}</p>
        </div>
      </div>
    </div>`;
}

function renderPositiveFindings(findings: string[]): string {
  if (!findings || findings.length === 0) return '';

  return `
    <section class="section" id="whats-working">
      <h2>What's Working Well</h2>
      <ul class="positive-list">
        ${findings.map(f => `<li>${escHtml(f)}</li>`).join('')}
      </ul>
    </section>`;
}

function renderPagesSummary(crawlPages: any[]): string {
  return `
    <section class="section" id="pages-audited">
      <h2>Pages Audited</h2>
      <table class="pages-table">
        <thead>
          <tr>
            <th>Page Type</th>
            <th>URL</th>
            <th>Load Time</th>
            <th>DataLayer</th>
            <th>GA4 Hits</th>
          </tr>
        </thead>
        <tbody>
          ${crawlPages.map(p => {
            const dl = safeParseJSON(p.datalayer_events, []);
            const ga4 = safeParseJSON(p.ga4_requests, []);
            const shortUrl = p.page_url.length > 60 ? p.page_url.substring(0, 57) + '…' : p.page_url;
            return `<tr>
              <td><span class="page-type-badge">${escHtml(p.page_type)}</span></td>
              <td class="url-cell"><a href="${escHtml(p.page_url)}" target="_blank" rel="noopener" title="${escHtml(p.page_url)}">${escHtml(shortUrl)}</a></td>
              <td>${(() => {
                const dcl = (p as any).dom_content_loaded_ms || 0;
                const total = p.page_load_ms || 0;
                // Use DOMContentLoaded time if available and meaningful
                const displayMs = dcl > 100 ? dcl : total;
                if (displayMs <= 100) return '<span style="color:#dc3545">Failed to load</span>';
                if (total >= 29000 && dcl > 100) return (dcl / 1000).toFixed(1) + 's';
                if (total >= 29000) return total / 1000 + 's+ (timeout)';
                return (displayMs / 1000).toFixed(1) + 's';
              })()}</td>
              <td>${dl.length}</td>
              <td>${ga4.length}</td>
            </tr>`;
          }).join('')}
        </tbody>
      </table>
    </section>`;
}

function renderLimitations(limitations: string[]): string {
  if (!limitations || limitations.length === 0) return '';

  return `
    <section class="section" id="limitations">
      <h2>Audit Limitations</h2>
      <p class="muted">The following aspects could not be fully verified during this automated crawl:</p>
      <ul class="limitations-list">
        ${limitations.map(l => `<li>${escHtml(l)}</li>`).join('')}
      </ul>
    </section>`;
}

function renderScreenshot(screenshotRelPath: string, caption: string): string {
  // Embed screenshot as base64 data URI so the report is fully self-contained
  const absolutePath = path.join(__dirname, '..', 'public', screenshotRelPath);
  try {
    if (fs.existsSync(absolutePath)) {
      const stat = fs.statSync(absolutePath);
      // Screenshots under 15KB are almost certainly blank/empty — show placeholder instead
      if (stat.size < 15000) {
        return `
    <div class="screenshot-container screenshot-unavailable">
      <div class="screenshot-placeholder">
        <p>Screenshot unavailable — page did not render during crawl.</p>
      </div>
      <p class="screenshot-caption">${escHtml(caption)}</p>
    </div>`;
      }
      const imageBuffer = fs.readFileSync(absolutePath);
      const base64 = imageBuffer.toString('base64');
      const mimeType = screenshotRelPath.endsWith('.png') ? 'image/png' : 'image/jpeg';
      return `
    <div class="screenshot-container">
      <img src="data:${mimeType};base64,${base64}" alt="${escHtml(caption)}" class="screenshot" loading="lazy" />
      <p class="screenshot-caption">${escHtml(caption)}</p>
    </div>`;
    }
  } catch { /* fall through to fallback */ }
  return '';
}

function renderFooter(audit: AuditRow, totalIssues: number, criticalOrHigh: number): string {
  // Build a dynamic CTA line based on findings
  let ctaLine = 'Ask us about <strong>Release Guard</strong> — automated tracking checks after every site change. Never ship broken analytics again.';
  if (totalIssues > 0 && criticalOrHigh > 0) {
    ctaLine = `This audit found ${totalIssues} issue${totalIssues !== 1 ? 's' : ''}, including ${criticalOrHigh} rated critical or high severity. <strong>Release Guard</strong> would have caught these automatically before they affected your reporting. Ask us about ongoing monitoring.`;
  } else if (totalIssues > 0) {
    ctaLine = `This audit found ${totalIssues} issue${totalIssues !== 1 ? 's' : ''}. <strong>Release Guard</strong> monitors your tracking continuously so issues like these are caught before they impact your data. Ask us about ongoing monitoring.`;
  }

  return `
    <footer class="report-footer">
      <div class="footer-cta">
        <h3>Want Ongoing Monitoring?</h3>
        <p>${ctaLine}</p>
      </div>
      <div class="footer-meta">
        <div class="brand brand-sm">Track<span class="brand-accent">Guard</span></div>
        <p>Report generated ${new Date().toLocaleDateString('en-IE', { day: 'numeric', month: 'long', year: 'numeric' })} · Ref: ${escHtml(audit.reference_id)}</p>
      </div>
    </footer>`;
}

// ─── CSS ────────────────────────────────────────────────────────────────────

function reportCSS(): string {
  return `
    :root {
      --navy: #1B2A4A;
      --navy-light: #2a3f6a;
      --teal: #2E8B8B;
      --teal-light: #e6f4f4;
      --red: #DC3545;
      --red-bg: #fdf0f0;
      --orange: #E67E22;
      --orange-bg: #fef5ec;
      --amber: #F0AD4E;
      --amber-bg: #fef9ec;
      --green: #28A745;
      --green-bg: #edf8ef;
      --gray-50: #f9fafb;
      --gray-100: #f3f4f6;
      --gray-200: #e5e7eb;
      --gray-300: #d1d5db;
      --gray-500: #6b7280;
      --gray-700: #374151;
      --gray-900: #111827;
      --font: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      --mono: 'SF Mono', 'Fira Code', 'Consolas', monospace;
    }

    * { margin: 0; padding: 0; box-sizing: border-box; }

    body {
      font-family: var(--font);
      color: var(--gray-900);
      background: var(--gray-50);
      line-height: 1.6;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    .report {
      max-width: 900px;
      margin: 0 auto;
      background: white;
    }

    /* Header */
    .report-header {
      background: var(--navy);
      color: white;
      padding: 40px 48px;
    }
    .brand { font-size: 18px; font-weight: 700; margin-bottom: 8px; }
    .brand-accent { color: var(--teal); }
    .brand-sm { font-size: 14px; }
    .report-header h1 { font-size: 28px; font-weight: 300; margin-bottom: 24px; }
    .header-meta { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
    .meta-label { display: block; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: rgba(255,255,255,0.6); }
    .meta-value { font-size: 14px; }

    /* Scorecard */
    .scorecard {
      display: flex;
      align-items: center;
      gap: 40px;
      padding: 40px 48px;
      border-bottom: 1px solid var(--gray-200);
    }
    .score-circle {
      width: 140px;
      height: 140px;
      border-radius: 50%;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }
    .score-green { background: var(--green-bg); border: 4px solid var(--green); }
    .score-amber { background: var(--amber-bg); border: 4px solid var(--amber); }
    .score-red { background: var(--red-bg); border: 4px solid var(--red); }
    .score-number { font-size: 48px; font-weight: 700; line-height: 1; }
    .score-green .score-number { color: var(--green); }
    .score-amber .score-number { color: var(--orange); }
    .score-red .score-number { color: var(--red); }
    .score-label { font-size: 12px; color: var(--gray-500); margin-top: 4px; }
    .score-breakdown { flex: 1; }
    .score-breakdown h2 { font-size: 18px; margin-bottom: 12px; color: var(--navy); }
    .severity-counts { display: flex; gap: 16px; margin-bottom: 16px; }
    .sev-count { text-align: center; padding: 8px 16px; border-radius: 8px; }
    .sev-critical { background: var(--red-bg); }
    .sev-high { background: var(--orange-bg); }
    .sev-medium { background: var(--amber-bg); }
    .sev-low { background: var(--gray-100); }
    .sev-none { background: var(--green-bg); }
    .sev-num { display: block; font-size: 24px; font-weight: 700; }
    .sev-critical .sev-num { color: var(--red); }
    .sev-high .sev-num { color: var(--orange); }
    .sev-medium .sev-num { color: var(--amber); }
    .sev-low .sev-num { color: var(--gray-500); }
    .sev-none .sev-num { color: var(--green); }
    .sev-label { font-size: 11px; color: var(--gray-500); text-transform: uppercase; }
    .category-pills { display: flex; flex-wrap: wrap; gap: 8px; }
    .cat-pill {
      font-size: 12px;
      padding: 4px 10px;
      border-radius: 12px;
      border: 1px solid var(--gray-200);
      color: var(--gray-700);
    }
    .cat-critical { border-color: var(--red); color: var(--red); background: var(--red-bg); }
    .cat-high { border-color: var(--orange); color: var(--orange); background: var(--orange-bg); }
    .cat-medium { border-color: var(--amber); color: #946200; background: var(--amber-bg); }

    /* How to read */
    .how-to-read {
      padding: 14px 48px;
      background: var(--gray-50);
      font-size: 13px;
      color: var(--gray-500);
      border-bottom: 1px solid var(--gray-200);
      line-height: 1.5;
    }

    /* Table of Contents */
    .toc {
      padding: 16px 48px;
      background: white;
      border-bottom: 1px solid var(--gray-200);
      display: flex;
      align-items: center;
      flex-wrap: wrap;
      gap: 8px;
    }
    .toc-label {
      font-size: 12px;
      font-weight: 600;
      color: var(--gray-500);
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-right: 4px;
    }
    .toc a {
      font-size: 13px;
      color: var(--teal);
      text-decoration: none;
      padding: 4px 12px;
      border-radius: 4px;
      background: var(--teal-light);
      transition: background 0.15s;
    }
    .toc a:hover { background: #cce8e8; }

    /* Data Impact (promoted) */
    .data-impact-section { padding: 24px 48px; }
    .data-impact-box {
      display: flex;
      gap: 20px;
      align-items: flex-start;
      background: linear-gradient(135deg, #fef5ec 0%, #fef9ec 100%);
      border: 2px solid var(--amber);
      border-radius: 10px;
      padding: 24px 28px;
    }
    .data-impact-icon { font-size: 32px; flex-shrink: 0; }
    .data-impact-content h2 { font-size: 18px; color: #946200; margin-bottom: 10px; }
    .data-impact-content p { font-size: 16px; line-height: 1.65; color: var(--gray-700); }

    /* Sections */
    .section { padding: 32px 48px; border-bottom: 1px solid var(--gray-200); }
    .section h2 { font-size: 20px; color: var(--navy); margin-bottom: 16px; }
    .section h3 { font-size: 16px; color: var(--navy); margin: 20px 0 10px; }
    .summary-box {
      background: var(--gray-50);
      border-left: 4px solid var(--navy);
      padding: 20px 24px;
      font-size: 15px;
      margin-bottom: 16px;
    }

    /* Consent */
    .consent-meta { display: flex; gap: 12px; margin-bottom: 20px; flex-wrap: wrap; }
    .consent-badge {
      padding: 6px 14px;
      border-radius: 6px;
      font-size: 13px;
      font-weight: 600;
      background: var(--gray-100);
      color: var(--gray-700);
    }
    .consent-ok { background: var(--green-bg); color: var(--green); }
    .consent-warn { background: var(--amber-bg); color: #946200; }
    .consent-table-wrap { overflow-x: auto; margin: 16px 0; }
    .consent-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 13px;
    }
    .consent-table th {
      background: var(--navy);
      color: white;
      padding: 10px 14px;
      text-align: left;
      font-weight: 600;
    }
    .consent-table td {
      padding: 8px 14px;
      border-bottom: 1px solid var(--gray-200);
    }
    .consent-table code { font-family: var(--mono); font-size: 12px; }
    .consent-cell-denied { color: var(--red); font-weight: 600; }
    .consent-cell-granted { color: var(--green); font-weight: 600; }
    .consent-cell-ok { color: var(--green); font-weight: 600; }
    .consent-cell-warn { color: var(--orange); font-weight: 600; }
    .consent-cell-missing { color: var(--gray-500); }

    /* Alert */
    .alert { padding: 16px 20px; border-radius: 8px; margin: 12px 0; }
    .alert-warning { background: var(--amber-bg); border-left: 4px solid var(--amber); }

    /* Issue cards */
    .category-group { margin-bottom: 24px; }
    .category-title { font-size: 16px; color: var(--navy-light); margin-bottom: 12px; padding-bottom: 8px; border-bottom: 2px solid var(--gray-200); }
    .issue-card {
      border: 1px solid var(--gray-200);
      border-radius: 8px;
      margin-bottom: 16px;
      overflow: hidden;
    }
    .issue-critical { border-left: 4px solid var(--red); }
    .issue-high { border-left: 4px solid var(--orange); }
    .issue-medium { border-left: 4px solid var(--amber); }
    .issue-low { border-left: 4px solid var(--gray-300); }
    .issue-header { padding: 14px 18px; background: var(--gray-50); display: flex; align-items: center; gap: 12px; }
    .issue-number {
      font-size: 11px;
      font-weight: 700;
      color: var(--gray-500);
      white-space: nowrap;
      text-transform: uppercase;
      letter-spacing: 0.03em;
    }
    .issue-title { font-size: 15px; font-weight: 600; }
    .severity-badge {
      font-size: 10px;
      font-weight: 700;
      padding: 3px 8px;
      border-radius: 4px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      white-space: nowrap;
    }
    .badge-critical { background: var(--red); color: white; }
    .badge-high { background: var(--orange); color: white; }
    .badge-medium { background: var(--amber); color: white; }
    .badge-low { background: var(--gray-300); color: var(--gray-700); }
    .issue-body { padding: 14px 18px; }
    .issue-section { margin-bottom: 12px; }
    .issue-section:last-child { margin-bottom: 0; }
    .issue-label { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: var(--gray-500); margin-bottom: 4px; }
    .issue-body p { font-size: 14px; color: var(--gray-700); }

    /* Positive findings */
    .positive-list { list-style: none; padding: 0; }
    .positive-list li {
      padding: 10px 14px 10px 36px;
      position: relative;
      border-bottom: 1px solid var(--gray-100);
      font-size: 14px;
    }
    .positive-list li:before { content: '✓'; position: absolute; left: 14px; color: var(--green); font-weight: 700; }

    /* Pages table */
    .pages-table { width: 100%; border-collapse: collapse; font-size: 13px; }
    .pages-table th {
      background: var(--gray-50);
      padding: 10px 12px;
      text-align: left;
      font-weight: 600;
      color: var(--gray-700);
      border-bottom: 2px solid var(--gray-200);
    }
    .pages-table td { padding: 8px 12px; border-bottom: 1px solid var(--gray-100); }
    .url-cell { font-family: var(--mono); font-size: 12px; }
    .url-cell a { color: var(--gray-500); text-decoration: none; }
    .url-cell a:hover { color: var(--teal); text-decoration: underline; }
    .page-type-badge {
      background: var(--teal-light);
      color: var(--teal);
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 12px;
      font-weight: 600;
    }

    /* Screenshots */
    .screenshot-container { margin: 20px 0; text-align: center; }
    .screenshot-placeholder {
      background: #f8f9fa; border: 2px dashed #ccc; border-radius: 8px;
      padding: 40px 20px; color: #888; font-style: italic; font-size: 0.95rem;
    }
    .screenshot {
      max-width: 100%;
      max-height: 600px;
      object-fit: contain;
      object-position: top;
      border: 1px solid var(--gray-200);
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    }
    .screenshot-caption { font-size: 12px; color: var(--gray-500); margin-top: 8px; font-style: italic; }

    /* Tag list */
    .tag-list { list-style: none; padding: 0; }
    .tag-list li { padding: 6px 0; font-size: 13px; border-bottom: 1px solid var(--gray-100); }
    .tag-list code { font-family: var(--mono); background: var(--gray-100); padding: 2px 6px; border-radius: 3px; font-size: 12px; }

    /* Limitations */
    .limitations-list { padding-left: 20px; }
    .limitations-list li { font-size: 14px; color: var(--gray-500); margin-bottom: 6px; }

    /* Muted */
    .muted { color: var(--gray-500); font-size: 13px; }

    /* Footer */
    .report-footer { padding: 32px 48px; background: var(--gray-50); }
    .footer-cta {
      background: var(--navy);
      color: white;
      padding: 24px 28px;
      border-radius: 8px;
      margin-bottom: 24px;
    }
    .footer-cta h3 { font-size: 18px; margin-bottom: 6px; }
    .footer-cta p { font-size: 14px; opacity: 0.85; }
    .footer-meta { text-align: center; }
    .footer-meta p { font-size: 12px; color: var(--gray-500); margin-top: 6px; }

    /* Print */
    @media print {
      body { background: white; }
      .report { max-width: none; box-shadow: none; }
      .section { break-inside: avoid; }
      .issue-card { break-inside: avoid; }
      .footer-cta { break-inside: avoid; }
    }

    /* Mobile */
    @media (max-width: 640px) {
      .report-header, .scorecard, .section, .report-footer { padding: 24px; }
      .scorecard { flex-direction: column; text-align: center; }
      .severity-counts { justify-content: center; }
      .header-meta { grid-template-columns: 1fr; }
    }
  `;
}

// ─── Utility ────────────────────────────────────────────────────────────────

function escHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function safeParseJSON(str: string | null, fallback: any): any {
  if (!str) return fallback;
  try {
    return JSON.parse(str);
  } catch {
    return fallback;
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// NEW: Deterministic Scorecard Report Builder
// ═══════════════════════════════════════════════════════════════════════════════

const CATEGORY_ORDER: CheckCategory[] = [
  'GA4 Detection',
  'GTM Detection',
  'Consent & Privacy',
  'Ecommerce Events',
  'Tag Health',
  'Page Coverage',
];

const STATUS_ICONS: Record<string, string> = {
  pass: '&#10003;',  // ✓
  fail: '&#10007;',  // ✗
  warn: '&#9888;',   // ⚠
  info: '&#8505;',   // ℹ
};

/**
 * Generate a compact scorecard HTML report from deterministic check results.
 * Self-contained HTML with inline CSS. No AI, no narrative.
 */
/** Deduplicate crawl_pages rows by URL. Keep the row with the higher dataLayer count. */
function deduplicateCrawlPages(pages: any[]): any[] {
  const byUrl = new Map<string, any>();
  for (const p of pages) {
    const existing = byUrl.get(p.page_url);
    if (!existing) {
      byUrl.set(p.page_url, p);
    } else {
      const existingDL = safeParseJSON(existing.datalayer_events, []).length;
      const currentDL = safeParseJSON(p.datalayer_events, []).length;
      if (currentDL > existingDL) {
        byUrl.set(p.page_url, p);
      }
    }
  }
  return Array.from(byUrl.values());
}

export function buildScorecardReport(
  audit: AuditRow,
  scorecard: ScorecardResult,
  consentData: ConsentResult | null
): string {
  const crawlPages = deduplicateCrawlPages(getCrawlPages(audit.id).filter(p => p.page_type !== 'consent_check'));
  const auditDate = new Date(audit.created_at).toLocaleDateString('en-IE', {
    day: 'numeric', month: 'long', year: 'numeric',
  });

  // Group checks by category (excluding overall_score)
  const checksByCategory = new Map<CheckCategory, CheckResult[]>();
  for (const cat of CATEGORY_ORDER) {
    checksByCategory.set(cat, []);
  }
  for (const check of scorecard.checks) {
    if (check.id === 'overall_score') continue;
    const list = checksByCategory.get(check.category as CheckCategory);
    if (list) list.push(check);
  }

  // Get homepage screenshot
  const homepageCrawl = crawlPages.find(p => p.page_type === 'homepage');
  const homepageScreenshot = homepageCrawl?.screenshot_path || null;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tracking Health Check — ${escHtml(audit.website_url)} | TrackGuard</title>
  <style>${scorecardCSS()}</style>
</head>
<body>
  <div class="report">
    ${renderScorecardHeader(audit, auditDate, scorecard)}
    ${renderCheckCategories(checksByCategory)}
    ${homepageScreenshot ? renderScorecardScreenshot(homepageScreenshot, 'Homepage at time of audit') : ''}
    ${renderScorecardPagesTable(crawlPages)}
    ${renderScorecardFooter(audit)}
  </div>
  <script>${scorecardJS()}</script>
</body>
</html>`;
}

function renderScorecardHeader(audit: AuditRow, auditDate: string, sc: ScorecardResult): string {
  const scoreColor = sc.score >= 80 ? 'score-green' : sc.score >= 50 ? 'score-amber' : 'score-red';

  return `
    <header class="report-header">
      <div class="header-top">
        <div class="brand">Track<span class="brand-accent">Guard</span></div>
        <h1>Tracking Health Check</h1>
      </div>
      <div class="header-meta">
        <div class="meta-item"><span class="meta-label">Website</span><span class="meta-value">${escHtml(audit.website_url)}</span></div>
        <div class="meta-item"><span class="meta-label">Company</span><span class="meta-value">${escHtml(audit.company_name)}</span></div>
        <div class="meta-item"><span class="meta-label">Date</span><span class="meta-value">${auditDate}</span></div>
        <div class="meta-item"><span class="meta-label">Reference</span><span class="meta-value">${escHtml(audit.reference_id)}</span></div>
      </div>
    </header>
    <section class="score-section">
      <div class="score-circle ${scoreColor}">
        <div class="score-number">${sc.score}</div>
        <div class="score-label">/ 100</div>
      </div>
      <div class="score-summary">
        <div class="score-counts">
          <span class="count-badge count-pass">${sc.passCount} passed</span>
          <span class="count-badge count-warn">${sc.warnCount} warning${sc.warnCount !== 1 ? 's' : ''}</span>
          <span class="count-badge count-fail">${sc.failCount} failure${sc.failCount !== 1 ? 's' : ''}</span>
          <span class="count-badge count-info">${sc.infoCount} info</span>
        </div>
      </div>
    </section>`;
}

function renderCheckCategories(checksByCategory: Map<CheckCategory, CheckResult[]>): string {
  let html = '<section class="checks-section">';

  for (const [category, checks] of checksByCategory) {
    if (checks.length === 0) continue;

    html += `
      <div class="category-group">
        <h2 class="category-title">${escHtml(category)}</h2>
        <div class="checks-list">`;

    for (const check of checks) {
      const hasDetails = check.details && Object.keys(check.details).length > 0;
      html += `
          <div class="check-row check-${check.status}${hasDetails ? ' expandable' : ''}"${hasDetails ? ' onclick="toggleDetails(this)"' : ''}>
            <div class="check-main">
              <span class="status-icon status-${check.status}">${STATUS_ICONS[check.status]}</span>
              <span class="check-name">${escHtml(check.name)}</span>
              <span class="check-summary">${escHtml(check.summary)}</span>
              ${hasDetails ? '<span class="expand-arrow">&#9660;</span>' : ''}
            </div>
            ${hasDetails ? `<div class="check-details">${renderCheckDetails(check)}</div>` : ''}
          </div>`;
    }

    html += `
        </div>
      </div>`;
  }

  html += '</section>';
  return html;
}

function renderCheckDetails(check: CheckResult): string {
  if (!check.details) return '';

  const d = check.details;
  const parts: string[] = [];

  // Render known detail types nicely
  if (d.measurement_ids) {
    parts.push(`<div class="detail-item"><strong>Measurement IDs:</strong> ${(d.measurement_ids as string[]).map(id => `<code>${escHtml(id)}</code>`).join(', ')}</div>`);
  }
  if (d.container_ids) {
    parts.push(`<div class="detail-item"><strong>Container IDs:</strong> ${(d.container_ids as string[]).map(id => `<code>${escHtml(id)}</code>`).join(', ')}</div>`);
  }
  if (d.ads_ids) {
    parts.push(`<div class="detail-item"><strong>Ads IDs:</strong> ${(d.ads_ids as string[]).map(id => `<code>${escHtml(id)}</code>`).join(', ')}</div>`);
  }
  if (d.tags) {
    parts.push(`<div class="detail-item"><strong>Tags:</strong> ${(d.tags as string[]).join(', ')}</div>`);
  }
  if (d.missing_pages) {
    parts.push(`<div class="detail-item"><strong>Missing pages:</strong><ul>${(d.missing_pages as any[]).map(p => `<li>${escHtml(p.page_type || 'unknown')}: <code>${escHtml(p.url)}</code></li>`).join('')}</ul></div>`);
  }
  if (d.affected_pages) {
    parts.push(`<div class="detail-item"><strong>Affected pages:</strong><ul>${(d.affected_pages as any[]).map(p => `<li>${escHtml(p.page_type || 'unknown')}: <code>${escHtml(p.url)}</code></li>`).join('')}</ul></div>`);
  }
  if (d.pages_with_duplicates) {
    parts.push(`<div class="detail-item"><strong>Pages with duplicates:</strong><ul>${(d.pages_with_duplicates as any[]).map(p => `<li>${escHtml(p.label)}: ${p.ids.map((id: string) => `<code>${escHtml(id)}</code>`).join(', ')}</li>`).join('')}</ul></div>`);
  }
  if (d.duplicate_pages) {
    parts.push(`<div class="detail-item"><strong>Duplicate page_view:</strong><ul>${(d.duplicate_pages as any[]).map(p => `<li>${escHtml(p.label)}: ${p.count} page_view events</li>`).join('')}</ul></div>`);
  }
  if (d.containers) {
    const containers = d.containers as Record<string, string[]>;
    parts.push(`<div class="detail-item"><strong>Containers by page:</strong><ul>${Object.entries(containers).map(([id, pages]) => `<li><code>${escHtml(id)}</code>: ${pages.join(', ')}</li>`).join('')}</ul></div>`);
  }
  if (d.changes) {
    const changes = d.changes as Record<string, { before: string; after: string }>;
    parts.push(`<div class="detail-item"><strong>Consent changes:</strong><table class="detail-table"><thead><tr><th>Parameter</th><th>Before</th><th>After</th></tr></thead><tbody>${Object.entries(changes).map(([k, v]) => `<tr><td><code>${escHtml(k)}</code></td><td>${escHtml(v.before)}</td><td>${escHtml(v.after)}</td></tr>`).join('')}</tbody></table></div>`);
  }
  if (d.defaults) {
    const defaults = d.defaults as Record<string, string>;
    if (Object.keys(defaults).length > 0) {
      parts.push(`<div class="detail-item"><strong>Default consent state:</strong> ${Object.entries(defaults).map(([k, v]) => `${k}=${v}`).join(', ')}</div>`);
    }
  }
  if (d.pre_consent_gcs && (d.pre_consent_gcs as string[]).length > 0) {
    parts.push(`<div class="detail-item"><strong>Pre-consent GCS values:</strong> ${[...new Set(d.pre_consent_gcs as string[])].map(g => `<code>${escHtml(g)}</code>`).join(', ')}</div>`);
  }
  if (d.pre_consent_count) {
    parts.push(`<div class="detail-item"><strong>Pre-consent GA4 requests:</strong> ${d.pre_consent_count}</div>`);
  }
  if (d.pages) {
    parts.push(`<div class="detail-item"><ul>${(d.pages as any[]).map(p => `<li>${escHtml(p.page_type || 'unknown')}: <code>${escHtml(p.url)}</code></li>`).join('')}</ul></div>`);
  }
  if (d.failed_pages) {
    parts.push(`<div class="detail-item"><strong>Failed:</strong><ul>${(d.failed_pages as any[]).map(p => `<li>${escHtml(p.page_type || 'unknown')}: <code>${escHtml(p.url)}</code></li>`).join('')}</ul></div>`);
  }
  if (d.times) {
    parts.push(`<div class="detail-item"><table class="detail-table"><thead><tr><th>Page</th><th>Load Time</th></tr></thead><tbody>${(d.times as any[]).map(t => `<tr><td>${escHtml(t.page)}</td><td>${escHtml(t.dcl_display)}</td></tr>`).join('')}</tbody></table></div>`);
  }
  if (d.pages_with_errors) {
    parts.push(`<div class="detail-item"><strong>Console errors:</strong><ul>${(d.pages_with_errors as any[]).map(p => `<li>${escHtml(p.page)}: ${p.errors.map((e: string) => `<code>${escHtml(e.substring(0, 120))}</code>`).join(', ')}</li>`).join('')}</ul></div>`);
  }
  if (d.events_checked) {
    parts.push(`<div class="detail-item"><strong>Events checked:</strong><ul>${(d.events_checked as any[]).map(e => `<li>${escHtml(e.event)} on ${escHtml(e.page)}: ${e.present.join(', ')}${e.missing.length > 0 ? ` (missing: ${e.missing.join(', ')})` : ''}</li>`).join('')}</ul></div>`);
  }
  if (d.events_with_issues) {
    parts.push(`<div class="detail-item"><strong>Issues:</strong><ul>${(d.events_with_issues as any[]).map(e => `<li>${escHtml(e.event)} on ${escHtml(e.page)}: missing ${e.missing.join(', ')}</li>`).join('')}</ul></div>`);
  }
  if (d.missing) {
    parts.push(`<div class="detail-item"><strong>Missing on:</strong><ul>${(d.missing as any[]).map(m => `<li><code>${escHtml(m.url)}</code></li>`).join('')}</ul></div>`);
  }

  return parts.join('');
}

function renderScorecardScreenshot(screenshotRelPath: string, caption: string): string {
  const absolutePath = path.join(__dirname, '..', 'public', screenshotRelPath);
  try {
    if (fs.existsSync(absolutePath)) {
      const stat = fs.statSync(absolutePath);
      if (stat.size < 15000) {
        return `<section class="screenshot-section"><div class="screenshot-placeholder"><p>Screenshot unavailable — page did not render during crawl.</p></div></section>`;
      }
      const imageBuffer = fs.readFileSync(absolutePath);
      const base64 = imageBuffer.toString('base64');
      const mimeType = screenshotRelPath.endsWith('.png') ? 'image/png' : 'image/jpeg';
      return `
    <section class="screenshot-section">
      <h2>Homepage Screenshot</h2>
      <img src="data:${mimeType};base64,${base64}" alt="${escHtml(caption)}" class="screenshot" loading="lazy" />
    </section>`;
    }
  } catch { /* skip */ }
  return '';
}

function renderScorecardPagesTable(crawlPages: any[]): string {
  return `
    <section class="pages-section">
      <h2>Pages Audited</h2>
      <table class="pages-table">
        <thead>
          <tr>
            <th>Type</th>
            <th>URL</th>
            <th>Load Time</th>
            <th>DataLayer</th>
            <th>GA4</th>
          </tr>
        </thead>
        <tbody>
          ${crawlPages.map(p => {
            const dl = safeParseJSON(p.datalayer_events, []);
            const ga4 = safeParseJSON(p.ga4_requests, []);
            const shortUrl = p.page_url.length > 55 ? p.page_url.substring(0, 52) + '…' : p.page_url;
            const dcl = (p as any).dom_content_loaded_ms || 0;
            const loadDisplay = dcl > 100 ? `${(dcl / 1000).toFixed(1)}s` : '<span class="text-red">Failed</span>';
            return `<tr>
              <td><span class="type-badge">${escHtml(p.page_type)}</span></td>
              <td class="url-cell"><a href="${escHtml(p.page_url)}" target="_blank" rel="noopener" title="${escHtml(p.page_url)}">${escHtml(shortUrl)}</a></td>
              <td>${loadDisplay}</td>
              <td>${dl.length}</td>
              <td>${ga4.length}</td>
            </tr>`;
          }).join('')}
        </tbody>
      </table>
    </section>`;
}

function renderScorecardFooter(audit: AuditRow): string {
  return `
    <footer class="report-footer">
      <p class="disclaimer">This scan captures externally observable tracking behaviour. It cannot access your GA4 property, GTM workspace, or verify server-side configurations. Conversion events requiring user interaction (purchase, add_to_cart) cannot be triggered by automated scans.</p>
      <div class="footer-brand">
        <div class="brand brand-sm">Track<span class="brand-accent">Guard</span></div>
        <p>Report generated ${new Date().toLocaleDateString('en-IE', { day: 'numeric', month: 'long', year: 'numeric' })} · Ref: ${escHtml(audit.reference_id)}</p>
      </div>
    </footer>`;
}

function scorecardJS(): string {
  return `
    function toggleDetails(el) {
      el.classList.toggle('expanded');
    }
  `;
}

function scorecardCSS(): string {
  return `
    :root {
      --navy: #1B2A4A;
      --navy-light: #2a3f6a;
      --teal: #2E8B8B;
      --teal-light: #e6f4f4;
      --red: #DC3545;
      --red-bg: #fdf0f0;
      --orange: #E67E22;
      --orange-bg: #fef5ec;
      --amber: #F0AD4E;
      --amber-bg: #fef9ec;
      --green: #28A745;
      --green-bg: #edf8ef;
      --blue: #3B82F6;
      --blue-bg: #eff6ff;
      --gray-50: #f9fafb;
      --gray-100: #f3f4f6;
      --gray-200: #e5e7eb;
      --gray-300: #d1d5db;
      --gray-500: #6b7280;
      --gray-700: #374151;
      --gray-900: #111827;
      --font: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      --mono: 'SF Mono', 'Fira Code', 'Consolas', monospace;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: var(--font); color: var(--gray-900); background: var(--gray-50); line-height: 1.5; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .report { max-width: 900px; margin: 0 auto; background: white; }

    /* Header */
    .report-header { background: var(--navy); color: white; padding: 32px 40px; }
    .header-top { margin-bottom: 20px; }
    .brand { font-size: 16px; font-weight: 700; margin-bottom: 4px; }
    .brand-accent { color: var(--teal); }
    .brand-sm { font-size: 13px; }
    .report-header h1 { font-size: 24px; font-weight: 300; }
    .header-meta { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
    .meta-label { display: block; font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; color: rgba(255,255,255,0.5); }
    .meta-value { font-size: 13px; }

    /* Score section */
    .score-section { display: flex; align-items: center; gap: 24px; padding: 28px 40px; border-bottom: 1px solid var(--gray-200); }
    .score-circle { width: 100px; height: 100px; border-radius: 50%; display: flex; flex-direction: column; align-items: center; justify-content: center; flex-shrink: 0; }
    .score-green { background: var(--green-bg); border: 3px solid var(--green); }
    .score-amber { background: var(--amber-bg); border: 3px solid var(--amber); }
    .score-red { background: var(--red-bg); border: 3px solid var(--red); }
    .score-number { font-size: 36px; font-weight: 700; line-height: 1; }
    .score-green .score-number { color: var(--green); }
    .score-amber .score-number { color: var(--orange); }
    .score-red .score-number { color: var(--red); }
    .score-label { font-size: 11px; color: var(--gray-500); }
    .score-counts { display: flex; gap: 8px; flex-wrap: wrap; }
    .count-badge { font-size: 12px; padding: 4px 10px; border-radius: 12px; font-weight: 600; }
    .count-pass { background: var(--green-bg); color: var(--green); }
    .count-warn { background: var(--orange-bg); color: var(--orange); }
    .count-fail { background: var(--red-bg); color: var(--red); }
    .count-info { background: var(--blue-bg); color: var(--blue); }

    /* Checks */
    .checks-section { padding: 0 40px 24px; }
    .category-group { margin-top: 24px; }
    .category-title { font-size: 15px; font-weight: 700; color: var(--navy); padding-bottom: 8px; border-bottom: 2px solid var(--gray-200); margin-bottom: 0; }
    .checks-list { }
    .check-row { border-bottom: 1px solid var(--gray-100); }
    .check-main { display: flex; align-items: center; gap: 10px; padding: 10px 0; font-size: 13px; }
    .expandable .check-main { cursor: pointer; }
    .expandable .check-main:hover { background: var(--gray-50); margin: 0 -8px; padding: 10px 8px; border-radius: 4px; }
    .status-icon { width: 22px; height: 22px; border-radius: 50%; display: inline-flex; align-items: center; justify-content: center; font-size: 12px; flex-shrink: 0; font-weight: 700; }
    .status-pass { background: var(--green-bg); color: var(--green); }
    .status-fail { background: var(--red-bg); color: var(--red); }
    .status-warn { background: var(--orange-bg); color: var(--orange); font-size: 14px; }
    .status-info { background: var(--blue-bg); color: var(--blue); font-size: 11px; }
    .check-name { font-weight: 600; color: var(--gray-900); white-space: nowrap; min-width: 180px; }
    .check-summary { color: var(--gray-500); flex: 1; }
    .expand-arrow { font-size: 10px; color: var(--gray-300); transition: transform 0.2s; flex-shrink: 0; }
    .expanded .expand-arrow { transform: rotate(180deg); }
    .check-details { display: none; padding: 0 0 12px 32px; font-size: 12px; color: var(--gray-700); }
    .expanded .check-details { display: block; }
    .detail-item { margin-bottom: 6px; }
    .detail-item ul { margin: 4px 0 0 16px; }
    .detail-item li { margin-bottom: 2px; }
    .detail-item code { font-family: var(--mono); font-size: 11px; background: var(--gray-100); padding: 1px 5px; border-radius: 3px; }
    .detail-table { border-collapse: collapse; margin: 4px 0; font-size: 12px; }
    .detail-table th, .detail-table td { padding: 4px 10px; border: 1px solid var(--gray-200); text-align: left; }
    .detail-table th { background: var(--gray-50); font-weight: 600; }

    /* Screenshot */
    .screenshot-section { padding: 24px 40px; border-top: 1px solid var(--gray-200); }
    .screenshot-section h2 { font-size: 15px; color: var(--navy); margin-bottom: 12px; }
    .screenshot { max-width: 100%; max-height: 500px; object-fit: contain; object-position: top; border: 1px solid var(--gray-200); border-radius: 6px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }
    .screenshot-placeholder { background: var(--gray-50); border: 2px dashed var(--gray-300); border-radius: 6px; padding: 30px; text-align: center; color: var(--gray-500); font-size: 13px; }

    /* Pages table */
    .pages-section { padding: 24px 40px; border-top: 1px solid var(--gray-200); }
    .pages-section h2 { font-size: 15px; color: var(--navy); margin-bottom: 12px; }
    .pages-table { width: 100%; border-collapse: collapse; font-size: 12px; }
    .pages-table th { background: var(--gray-50); padding: 8px 10px; text-align: left; font-weight: 600; color: var(--gray-700); border-bottom: 2px solid var(--gray-200); }
    .pages-table td { padding: 6px 10px; border-bottom: 1px solid var(--gray-100); }
    .url-cell { font-family: var(--mono); font-size: 11px; }
    .url-cell a { color: var(--gray-500); text-decoration: none; }
    .url-cell a:hover { color: var(--teal); text-decoration: underline; }
    .type-badge { background: var(--teal-light); color: var(--teal); padding: 2px 6px; border-radius: 3px; font-size: 11px; font-weight: 600; }
    .text-red { color: var(--red); }

    /* Footer */
    .report-footer { padding: 24px 40px; background: var(--gray-50); border-top: 1px solid var(--gray-200); }
    .disclaimer { font-size: 11px; color: var(--gray-500); line-height: 1.5; margin-bottom: 16px; }
    .footer-brand { text-align: center; }
    .footer-brand p { font-size: 11px; color: var(--gray-500); margin-top: 4px; }

    /* Print */
    @media print {
      body { background: white; }
      .report { max-width: none; box-shadow: none; }
      .category-group { break-inside: avoid; }
      .check-details { display: block !important; }
      .expand-arrow { display: none; }
    }

    /* Mobile */
    @media (max-width: 640px) {
      .report-header, .score-section, .checks-section, .pages-section, .screenshot-section, .report-footer { padding-left: 20px; padding-right: 20px; }
      .score-section { flex-direction: column; text-align: center; }
      .check-main { flex-wrap: wrap; }
      .check-name { min-width: auto; }
      .header-meta { grid-template-columns: 1fr; }
    }
  `;
}
